import Header from '@/components/header/Header';
import './globals.css';
import Footer from '@/components/footer/Footer';
import { SearchProvider } from '@/context/SearchContext';
import { CollegeProvider } from '@/context/CollegContext';
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SearchProvider>
          <CollegeProvider>
          <Header />
          {children}
          <Analytics />
          <SpeedInsights />
          <Footer />
          </CollegeProvider>
        </SearchProvider>
      </body>
    </html>
  )
}
